/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.Cashier;

import java.awt.CardLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.awt.print.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import my.TwoWaySerialComm;
/**
 *
 * @author Watusi
 */
public class mainFrame extends javax.swing.JFrame {
    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();
        next_btn.setVisible(false);
        prev_btn.setVisible(false);
        NextLabel.setVisible(false);
        PrevLabel.setVisible(false);
        ImageIcon image = new ImageIcon(getClass().getResource("/my/Passer_2017.jpg"));
        Image my_image = image.getImage();
        Image resized_image = my_image.getScaledInstance(106, 133,  java.awt.Image.SCALE_SMOOTH);
        ImageIcon profilepic = new ImageIcon(resized_image);
        profilepic_label.setIcon(profilepic);
//        connect();
        PrinterJob job = PrinterJob.getPrinterJob();
//        insert("Uzumaki Naruto","202","CpE","2018-2019","link");
        
    }
    int count = 0;
    String pname = null;
    String psn = null;
    String pcourse = null;
    String psy = null;
    String ppp = null;
    String cpnumber = null;
    int spaceadded = 0;
    boolean flag = false;
    boolean prevpressed = false;
    ArrayList<String> req = new ArrayList<>();
    Map<String, String> reqprices = new HashMap<>();

        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        mainPanel = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sn_field = new javax.swing.JTextField();
        panel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        profilepic_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sn_textfield = new javax.swing.JLabel();
        name_textfield = new javax.swing.JLabel();
        course_textfield = new javax.swing.JLabel();
        sy_textfield = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tor = new javax.swing.JCheckBox();
        cet = new javax.swing.JCheckBox();
        cog = new javax.swing.JCheckBox();
        deploma = new javax.swing.JCheckBox();
        gmc = new javax.swing.JCheckBox();
        so = new javax.swing.JCheckBox();
        panel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        req1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        req3 = new javax.swing.JLabel();
        req2 = new javax.swing.JLabel();
        req4 = new javax.swing.JLabel();
        req6 = new javax.swing.JLabel();
        req5 = new javax.swing.JLabel();
        req1price = new javax.swing.JLabel();
        req2price = new javax.swing.JLabel();
        req3price = new javax.swing.JLabel();
        req4price = new javax.swing.JLabel();
        req5price = new javax.swing.JLabel();
        req6price = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        reqTotal = new javax.swing.JLabel();
        panel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        no_btn = new javax.swing.JButton();
        yes_btn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        prev_btn = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cancel_btn = new javax.swing.JButton();
        Proceed_Label = new javax.swing.JLabel();
        NextLabel = new javax.swing.JLabel();
        PrevLabel = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.UTILITY);

        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        panel1.setBackground(new java.awt.Color(0, 102, 0));
        panel1.setMaximumSize(new java.awt.Dimension(800, 400));
        panel1.setMinimumSize(new java.awt.Dimension(800, 400));
        panel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("to");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel9.setBackground(new java.awt.Color(0, 102, 204));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("WELCOME!");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Computerized");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Document Request Slip");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel11.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(191, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        mainPanel.add(panel1, "card2");

        panel2.setMaximumSize(new java.awt.Dimension(800, 400));
        panel2.setMinimumSize(new java.awt.Dimension(800, 400));
        panel2.setPreferredSize(new java.awt.Dimension(800, 400));
        panel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 400));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 400));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel2.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter your");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Student Number");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        sn_field.setFont(new java.awt.Font("Waree", 1, 36)); // NOI18N
        sn_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sn_field.setMinimumSize(new java.awt.Dimension(7, 15));
        sn_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sn_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(sn_field, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(289, 289, 289))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(81, 81, 81)
                .addComponent(sn_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        panel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        mainPanel.add(panel2, "card3");

        panel3.setBackground(new java.awt.Color(0, 102, 0));
        panel3.setMaximumSize(new java.awt.Dimension(800, 400));
        panel3.setMinimumSize(new java.awt.Dimension(800, 400));
        panel3.setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel4.setMaximumSize(new java.awt.Dimension(750, 550));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(750, 550));

        profilepic_label.setBackground(new java.awt.Color(255, 102, 255));
        profilepic_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Noto Sans CJK KR Regular", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Name:");

        jLabel12.setFont(new java.awt.Font("Noto Sans Mono CJK KR Regular", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Course:");

        jLabel13.setFont(new java.awt.Font("Noto Sans Mono CJK KR Regular", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Graduated S.Y.:");

        jLabel14.setFont(new java.awt.Font("Noto Sans Mono CJK KR Regular", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("Student #:");

        sn_textfield.setFont(new java.awt.Font("Noto Sans CJK KR Bold", 3, 24)); // NOI18N
        sn_textfield.setForeground(new java.awt.Color(255, 255, 255));
        sn_textfield.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sn_textfield.setAlignmentX(0.5F);
        sn_textfield.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        sn_textfield.setIconTextGap(8);
        sn_textfield.setMaximumSize(new java.awt.Dimension(4, 40));
        sn_textfield.setMinimumSize(new java.awt.Dimension(4, 40));
        sn_textfield.setPreferredSize(new java.awt.Dimension(4, 40));

        name_textfield.setFont(new java.awt.Font("Noto Sans CJK KR Bold", 3, 24)); // NOI18N
        name_textfield.setForeground(new java.awt.Color(255, 255, 255));
        name_textfield.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name_textfield.setAlignmentX(0.5F);
        name_textfield.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        name_textfield.setIconTextGap(8);
        name_textfield.setMaximumSize(new java.awt.Dimension(4, 40));
        name_textfield.setMinimumSize(new java.awt.Dimension(4, 40));
        name_textfield.setPreferredSize(new java.awt.Dimension(4, 40));

        course_textfield.setFont(new java.awt.Font("Noto Sans CJK KR Bold", 3, 24)); // NOI18N
        course_textfield.setForeground(new java.awt.Color(255, 255, 255));
        course_textfield.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        course_textfield.setAlignmentX(0.5F);
        course_textfield.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        course_textfield.setIconTextGap(8);
        course_textfield.setMaximumSize(new java.awt.Dimension(4, 20));
        course_textfield.setMinimumSize(new java.awt.Dimension(4, 20));
        course_textfield.setPreferredSize(new java.awt.Dimension(4, 40));

        sy_textfield.setFont(new java.awt.Font("Noto Sans CJK KR Bold", 3, 24)); // NOI18N
        sy_textfield.setForeground(new java.awt.Color(255, 255, 255));
        sy_textfield.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sy_textfield.setAlignmentX(0.5F);
        sy_textfield.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        sy_textfield.setIconTextGap(8);
        sy_textfield.setMaximumSize(new java.awt.Dimension(4, 40));
        sy_textfield.setMinimumSize(new java.awt.Dimension(4, 40));
        sy_textfield.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilepic_label, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(course_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(name_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sy_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(sn_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(sn_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(course_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(profilepic_label, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(sy_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(280, 280, 280))
        );

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        mainPanel.add(panel3, "card4");

        panel4.setBackground(new java.awt.Color(0, 102, 0));
        panel4.setMaximumSize(new java.awt.Dimension(800, 400));
        panel4.setMinimumSize(new java.awt.Dimension(800, 400));
        panel4.setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "What Type of Document Do You Want to Process?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Waree", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(888, 182));

        tor.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        tor.setForeground(new java.awt.Color(255, 255, 255));
        tor.setText("Transcript of Records");
        tor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torActionPerformed(evt);
            }
        });

        cet.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        cet.setForeground(new java.awt.Color(255, 255, 255));
        cet.setText("CET");
        cet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetActionPerformed(evt);
            }
        });

        cog.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        cog.setForeground(new java.awt.Color(255, 255, 255));
        cog.setText("Cert. of Granduation");
        cog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cogActionPerformed(evt);
            }
        });

        deploma.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        deploma.setForeground(new java.awt.Color(255, 255, 255));
        deploma.setText("Deploma");
        deploma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deplomaActionPerformed(evt);
            }
        });

        gmc.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        gmc.setForeground(new java.awt.Color(255, 255, 255));
        gmc.setText("Good Moral Character");
        gmc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmcActionPerformed(evt);
            }
        });

        so.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        so.setForeground(new java.awt.Color(255, 255, 255));
        so.setText("Special Orders");
        so.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tor)
                    .addComponent(cog)
                    .addComponent(cet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deploma)
                    .addComponent(gmc)
                    .addComponent(so))
                .addGap(12, 12, 12))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(tor)
                        .addGap(18, 18, 18)
                        .addComponent(cet)
                        .addGap(18, 18, 18)
                        .addComponent(cog))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(deploma)
                        .addGap(18, 18, 18)
                        .addComponent(gmc)
                        .addGap(18, 18, 18)
                        .addComponent(so)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        mainPanel.add(panel4, "card6");

        panel5.setBackground(new java.awt.Color(0, 102, 0));
        panel5.setMaximumSize(new java.awt.Dimension(800, 400));
        panel5.setMinimumSize(new java.awt.Dimension(800, 400));
        panel5.setPreferredSize(new java.awt.Dimension(800, 400));
        panel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 0));

        req1.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        req1.setText("4tr43rt4");
        req1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total Processing");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        req3.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        req3.setText("jLabel15");

        req2.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        req2.setText("jLabel15");

        req4.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        req4.setText("jLabel15");

        req6.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        req6.setText("jLabel15");

        req5.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        req5.setText("jLabel15");

        req1price.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req1price.setText("jLabel15");

        req2price.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req2price.setText("jLabel15");

        req3price.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req3price.setText("jLabel15");

        req4price.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req4price.setText("jLabel15");

        req5price.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req5price.setText("jLabel15");

        req6price.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        req6price.setText("jLabel15");

        jLabel15.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel15.setText("Total:");

        reqTotal.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        reqTotal.setText("jLabel16");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(req6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(req5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(req4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(req2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(req3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(req1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(180, 180, 180)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(req6price, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(req5price, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(req4price, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(req2price, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(req3price, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(req1price, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reqTotal))
                .addGap(97, 97, 97))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(req1price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(req2price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(req3price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(req4price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(req5price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(req6price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(req1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(req2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(req3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(req4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(req5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(req6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addComponent(reqTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel5.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        mainPanel.add(panel5, "card7");

        panel6.setBackground(new java.awt.Color(0, 102, 0));
        panel6.setMaximumSize(new java.awt.Dimension(800, 400));
        panel6.setMinimumSize(new java.awt.Dimension(800, 400));
        panel6.setPreferredSize(new java.awt.Dimension(800, 400));
        panel6.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Documents you have requested");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panel6.add(jLabel6, java.awt.BorderLayout.CENTER);

        mainPanel.add(panel6, "card7");

        panel7.setMaximumSize(new java.awt.Dimension(800, 400));
        panel7.setMinimumSize(new java.awt.Dimension(800, 400));
        panel7.setPreferredSize(new java.awt.Dimension(800, 400));
        panel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 102, 0));

        jLabel7.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Transactions?");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel7.setName(""); // NOI18N
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel16.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Do you have any other");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel16.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel16.setName(""); // NOI18N
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        no_btn.setText("No");
        no_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_btn.setPreferredSize(new java.awt.Dimension(111, 23));
        no_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        no_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_btnActionPerformed(evt);
            }
        });

        yes_btn.setText("Yes");
        yes_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        yes_btn.setPreferredSize(new java.awt.Dimension(111, 23));
        yes_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        yes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(yes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(no_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(no_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(331, Short.MAX_VALUE)))
        );

        panel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        mainPanel.add(panel7, "card7");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel10, "card9");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setMaximumSize(new java.awt.Dimension(800, 100));
        jPanel5.setMinimumSize(new java.awt.Dimension(287800, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(800, 100));

        prev_btn.setBackground(new java.awt.Color(0, 204, 255));
        prev_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Cashier/left-arrow (64).png"))); // NOI18N
        prev_btn.setBorderPainted(false);
        prev_btn.setContentAreaFilled(false);
        prev_btn.setFocusCycleRoot(true);
        prev_btn.setFocusTraversalPolicyProvider(true);
        prev_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prev_btn.setPreferredSize(new java.awt.Dimension(150, 80));
        prev_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Cashier/left-arrow (32).png"))); // NOI18N
        prev_btn.setRolloverEnabled(true);
        prev_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        prev_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_btnActionPerformed(evt);
            }
        });
        jPanel5.add(prev_btn);

        btn1.setBackground(new java.awt.Color(0, 102, 51));
        btn1.setForeground(new java.awt.Color(204, 204, 204));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Cashier/proceed.png"))); // NOI18N
        btn1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setFocusPainted(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setPreferredSize(new java.awt.Dimension(150, 80));
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Cashier/right-arrow (128).png"))); // NOI18N
        btn1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel5.add(btn1);

        next_btn.setBackground(new java.awt.Color(0, 204, 255));
        next_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Cashier/right-arrow (64).png"))); // NOI18N
        next_btn.setBorderPainted(false);
        next_btn.setContentAreaFilled(false);
        next_btn.setFocusCycleRoot(true);
        next_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        next_btn.setPreferredSize(new java.awt.Dimension(150, 80));
        next_btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Cashier/right-arrow (32).png"))); // NOI18N
        next_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });
        jPanel5.add(next_btn);

        cancel_btn.setBackground(new java.awt.Color(204, 51, 0));
        cancel_btn.setForeground(new java.awt.Color(204, 204, 204));
        cancel_btn.setText("Cancel");
        cancel_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancel_btn.setBorderPainted(false);
        cancel_btn.setFocusPainted(false);
        cancel_btn.setFocusable(false);
        cancel_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancel_btn.setPreferredSize(new java.awt.Dimension(100, 30));
        cancel_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        Proceed_Label.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        Proceed_Label.setText("Proceed");

        NextLabel.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        NextLabel.setText("Next");

        PrevLabel.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        PrevLabel.setText("Prev");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(PrevLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(Proceed_Label)
                .addGap(125, 125, 125)
                .addComponent(NextLabel)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 361, Short.MAX_VALUE)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 362, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proceed_Label)
                    .addComponent(NextLabel)
                    .addComponent(PrevLabel))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 73, Short.MAX_VALUE)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 74, Short.MAX_VALUE)))
        );

        jPanel5.add(jPanel6);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_btnActionPerformed
        String YourString = "Name:" + pname + "\t  Course&Year: " + pcourse + " " + psy + "\nStudentNumber:" + psn + "\nRequested Documents:\n\t" + req.get(0)
                + "\n\t" + req.get(1) + "\n\t" + req.get(2) + "\n\t" + req.get(3) + "\n\t" + req.get(4) + "\n\t" + req.get(5); //define and set contents of your string - remember about formating with \n if you want to have it split on lines
    jTextArea1.setLineWrap(true); //set line wrap for YourTextArea - this will prevent too long lines to be cut - they will be wrapaed to next line
    jTextArea1.append(YourString); //append YourString to YourTextArea 
        try {
        jTextArea1.print();
            try {
                my.TwoWaySerialComm.send.write(cpnumber.getBytes());
            } catch (IOException ex) {
                Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.first(mainPanel);
        flag = false;
        count = 0;
        prevpressed=false;
        req.clear();
        btn1.setVisible(true);
        next_btn.setVisible(false);
        prev_btn.setVisible(false);
        tor.setSelected(false);
        cet.setSelected(false);
        cog.setSelected(false);
        deploma.setSelected(false);
        gmc.setSelected(false);
        so.setSelected(false);
        Proceed_Label.setVisible(true);
        NextLabel.setVisible(false);
        PrevLabel.setVisible(false);
           //jTextArea1.print(null, null, false, null, null, false); //this will display print dialog that will lead you to print contents of YourTextArea so in efect contents of YourString
        } catch (PrinterException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_no_btnActionPerformed

    private void yes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_btnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        btn1.setVisible(false);
        next_btn.setVisible(true);
        prev_btn.setVisible(true);
        PrevLabel.setVisible(true);
        NextLabel.setVisible(true);
        prev_btn.setEnabled(false);
        count= 3;
        card.show(mainPanel,"card6");
    }//GEN-LAST:event_yes_btnActionPerformed

    private void prev_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_btnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.previous(mainPanel);
        count--;
        prevpressed = true;
        flag = false;
        if(count ==3){
//            count = 0;
//            btn1.setVisible(true);
//            next_btn.setVisible(false);
            prev_btn.setEnabled(false);
            PrevLabel.setVisible(false);
        }
    }//GEN-LAST:event_prev_btnActionPerformed

    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        if(prevpressed){
            prevpressed = false;
            //card.next(mainPanel);
        }
        if(!flag){count++;}
        if(count == 4){
           
            if(!req.isEmpty()){
                prev_btn.setEnabled(true);
                PrevLabel.setVisible(true);
                flag = false;
                reqprices.put(tor.getText(),"250");
                reqprices.put(cet.getText(),"150");
                reqprices.put(cog.getText(),"300");
                reqprices.put(deploma.getText(),"280");
                reqprices.put(gmc.getText(),"220");
                reqprices.put(so.getText(),"200");
                int reqsize = req.size();
                if(reqsize < 7){
                for(int i=0;i<6-reqsize;i++){
                    req.add(" ");
                }
                spaceadded = 6-reqsize;
                }
                
                while(req.indexOf(" ") >= 0){
                   req.remove(" ");
                }

                reqsize = req.size();
                for(int i=0;i<6-reqsize;i++){
                    req.add(" ");
                }
                
                System.out.println(req);
                req1.setText(req.get(0));
                req1price.setText(reqprices.get(req.get(0)));
                req2.setText(req.get(1));
                req2price.setText(reqprices.get(req.get(1)));
                req3.setText(req.get(2));
                req3price.setText(reqprices.get(req.get(2)));
                req4.setText(req.get(3));
                req4price.setText(reqprices.get(req.get(3)));
                req5.setText(req.get(4));
                req5price.setText(reqprices.get(req.get(4)));
                req6.setText(req.get(5));
                req6price.setText(reqprices.get(req.get(5)));
                int total = 0;
                for(int i=0;i<req.size();i++){
                    if(req.get(i) != " "){
                        total = total + Integer.parseInt(reqprices.get(req.get(i)));
                    }
                }
                
                reqTotal.setText(Integer.toString(total));
                card.next(mainPanel);
            }
            else{
                flag = true;
               
            }
        }
        
        if(count ==5){
            card.next(mainPanel);
            prev_btn.setEnabled(true);
            //NextLabel.setVisible(false);
            PrevLabel.setVisible(true);
            //count = 0;

   
        }
        if(count ==5){
            card.next(mainPanel);
            next_btn.setVisible(false);
            prev_btn.setVisible(false);
            NextLabel.setVisible(false);
            PrevLabel.setVisible(false);
              }

    }//GEN-LAST:event_next_btnActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        if(count == 0 ){
            card.next(mainPanel);
        }
        if(!flag){
            count++;
        }
        
       if (count == 2){
            String sn = sn_field.getText();
            if(!sn.isEmpty()){
            
            sn_field.setText("");
            System.out.println(sn);
                if(selectAll(sn)){
                    name_textfield.setText(pname);
                    sn_textfield.setText(psn);
                    course_textfield.setText(pcourse);
                    sy_textfield.setText(psy);
                    flag = false;
                    card.next(mainPanel);
                }
                else{
                    flag = true;
                }

            }
            else{
            flag = true;
            System.out.println("No SN");
            }
        }
       else if(count ==3){
            btn1.setVisible(false);
            Proceed_Label.setVisible(false);
            next_btn.setVisible(true);
            prev_btn.setVisible(true);
            prev_btn.setEnabled(false);
            NextLabel.setVisible(true);
            card.next(mainPanel);
            
        }

    }//GEN-LAST:event_btn1ActionPerformed

    private void sn_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sn_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sn_fieldActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.first(mainPanel);
        flag = false;
        count = 0;
        prevpressed=false;
        req.clear();
        btn1.setVisible(true);
        next_btn.setVisible(false);
        prev_btn.setVisible(false);
        tor.setSelected(false);
        cet.setSelected(false);
        cog.setSelected(false);
        deploma.setSelected(false);
        gmc.setSelected(false);
        so.setSelected(false);
        Proceed_Label.setVisible(true);
        NextLabel.setVisible(false);
        PrevLabel.setVisible(false);
        
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void torActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torActionPerformed
            if(tor.isSelected()){
                req.add(tor.getText());
            }
            else{
                req.remove(tor.getText());
           }
    }//GEN-LAST:event_torActionPerformed

    private void cetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetActionPerformed
        if(cet.isSelected()){
                req.add(cet.getText());
            }
            else{
                req.remove(cet.getText());
           }
    }//GEN-LAST:event_cetActionPerformed

    private void cogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cogActionPerformed
        if(cog.isSelected()){
                req.add(cog.getText());
            }
            else{
                req.remove(cog.getText());
           }
    }//GEN-LAST:event_cogActionPerformed

    private void deplomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deplomaActionPerformed
        if(deploma.isSelected()){
                req.add(deploma.getText());
            }
            else{
                req.remove(deploma.getText());
           }
    }//GEN-LAST:event_deplomaActionPerformed

    private void gmcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmcActionPerformed
        if(gmc.isSelected()){
                req.add(gmc.getText());
            }
            else{
                req.remove(gmc.getText());
           }
    }//GEN-LAST:event_gmcActionPerformed

    private void soActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soActionPerformed
         if(so.isSelected()){
                req.add(so.getText());
            }
            else{
                req.remove(so.getText());
           }
    }//GEN-LAST:event_soActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void connectdb() {
        Connection conn = null;
        try {
            // db parameters
            String url = "jdbc:sqlite::resource:my/students.db";
            // create a connection to the database
            conn = DriverManager.getConnection(url);
            
            System.out.println("Connection to SQLite has been established.");
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    public static void createNewDatabase() {
 
        String url = "jdbc:sqlite::resource:my/students.db";
 
        try (Connection conn = DriverManager.getConnection(url)) {
            if (conn != null) {
                DatabaseMetaData meta = conn.getMetaData();
                System.out.println("The driver name is " + meta.getDriverName());
                System.out.println("A new database has been created.");
            }
 
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    public static void createNewTable() {
        // SQLite connection string
        String url = "jdbc:sqlite::resource:my/students.db";
        
        // SQL statement for creating a new table
        String sql = "CREATE TABLE IF NOT EXISTS record (\n"
                + "	id integer PRIMARY KEY,\n"
                + "	name text NOT NULL,\n"
                + "	sn text NOT NULL,\n"
                + "	course text NOT NULL,\n"
                + "	sy text NOT NULL\n,"
                + "	pp text NOT NULL\n"
                + ");";
        
        try (Connection conn = DriverManager.getConnection(url);
                Statement stmt = conn.createStatement()) {
            // create a new table
            stmt.execute(sql);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private Connection connect() {
        // SQLite connection string
        String url = "jdbc:sqlite::resource:my/students.db";
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return conn;
    }
    public void insert(String name, String sn, String course, String sy, String lnk) {
        String sql = "INSERT INTO record(name,sn,course,sy,pp) VALUES(?,?,?,?,?)";
 
        try (Connection conn = this.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, name);
            pstmt.setString(2, sn);
            pstmt.setString(3, course);
            pstmt.setString(4, sy);
            pstmt.setString(5, lnk);
            pstmt.executeUpdate();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public boolean selectAll(String sn_key){
        String sql = "SELECT * FROM record WHERE sn =" +sn_key;
        
        try (Connection conn = this.connect();
             Statement stmt  = conn.createStatement();
             ResultSet rs    = stmt.executeQuery(sql)){
           
            // loop through the result set
            //System.out.println(rs.next());
            if(rs.next()) {
                pname = rs.getString("name");
                psn = rs.getString("sn");
                pcourse = rs.getString("course");
                psy = rs.getString("sy");
                ppp = rs.getString("pp");
                cpnumber = rs.getString("cpnumber");
                
                return true;

            }
            else{
                return false;
            }
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return false;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        createNewTable();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
                
            }
        });
        my.TwoWaySerialComm Serial = new my.TwoWaySerialComm();
        
        try {
            Serial.connect("/dev/ttyUSB0");
        } catch (Exception ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NextLabel;
    private javax.swing.JLabel PrevLabel;
    private javax.swing.JLabel Proceed_Label;
    private javax.swing.JButton btn1;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JCheckBox cet;
    private javax.swing.JCheckBox cog;
    private javax.swing.JLabel course_textfield;
    private javax.swing.JCheckBox deploma;
    private javax.swing.JCheckBox gmc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel name_textfield;
    private javax.swing.JButton next_btn;
    private javax.swing.JButton no_btn;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JButton prev_btn;
    private javax.swing.JLabel profilepic_label;
    private javax.swing.JLabel req1;
    private javax.swing.JLabel req1price;
    private javax.swing.JLabel req2;
    private javax.swing.JLabel req2price;
    private javax.swing.JLabel req3;
    private javax.swing.JLabel req3price;
    private javax.swing.JLabel req4;
    private javax.swing.JLabel req4price;
    private javax.swing.JLabel req5;
    private javax.swing.JLabel req5price;
    private javax.swing.JLabel req6;
    private javax.swing.JLabel req6price;
    private javax.swing.JLabel reqTotal;
    private javax.swing.JTextField sn_field;
    private javax.swing.JLabel sn_textfield;
    private javax.swing.JCheckBox so;
    private javax.swing.JLabel sy_textfield;
    private javax.swing.JCheckBox tor;
    private javax.swing.JButton yes_btn;
    // End of variables declaration//GEN-END:variables

}
